# Generated by Django 4.2.15 on 2026-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_computerskills_user_alter_language_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='language',
            name='reading_proficiency',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='speaking_proficiency',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='writing_proficiency',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
