# Generated by Django 4.2.15 on 2026-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_remove_language_proficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinformation',
            name='residential_city',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='addressinformation',
            name='residential_postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='addressinformation',
            name='residential_province',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='addressinformation',
            name='residential_street_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
