# Generated by Django 4.2.15 on 2026-09-04 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0025_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers_license', models.FileField(blank=True, null=True, upload_to='static/profiles/documents/')),
                ('id_document', models.FileField(blank=True, null=True, upload_to='static/profiles/documents/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='static/profiles/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
