"""
Django settings for mictseta_recruitment_system project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production (Render), set SECRET_KEY as an environment variable instead
# of relying on this fallback.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-+5d78i2gower*d@*0r3cl-q^r&@n=y8(m!kau8-4)q0-rw073$',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['058a-102-64-32-230.ngrok-free.app', '127.0.0.1', '192.168.1.195']

# Render sets this automatically to the service's *.onrender.com hostname.
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Comma-separated list of any other hosts to allow (e.g. a custom domain).
_extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS.extend(h.strip() for h in _extra_hosts.split(',') if h.strip())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'dbbackup',
    'authenticate',
    'home',
    'profiles',
    'users',
    'jobs',
    'dashboard',
    'job_seeker',
    'task_manager',
    'easyaudit',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'mictseta_recruitment_system.middleware.CsrfCookieMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
]

ROOT_URLCONF = 'mictseta_recruitment_system.urls'
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken',
    'x-requested-with',
    'csrfmiddlewaretoken',
    'csrftoken',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# # Ensure CSRF_COOKIE_HTTPONLY is True for enhanced security
# CSRF_COOKIE_HTTPONLY = False

# # Ensure CSRF_COOKIE_SECURE is True if using HTTPS
# CSRF_COOKIE_SECURE = True

# # Set CSRF_TRUSTED_ORIGINS if you have specific trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://058a-102-64-32-230.ngrok-free.app',
    'http://192.168.1.195:8000',
    'http://127.0.0.1:8000',
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# # Ensure CSRF_USE_SESSIONS is True to use CSRF tokens stored in session
# CSRF_USE_SESSIONS = True

# # Ensure CSRF_FAILURE_VIEW is set to handle CSRF failures
# # CSRF_FAILURE_VIEW = 'your_app.views.csrf_failure'  # Replace with your actual view name

# # Ensure CSRF_COOKIE_SAMESITE is 'Strict' or 'Lax' based on your requirements
# CSRF_COOKIE_SAMESITE = 'Strict'

CORS_ORIGIN_ALLOW_ALL = True
# # CSRF_TRUSTED_ORIGINS = ['https://058a-102-64-32-230.ngrok-free.app']

# # settings.py



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mictseta_recruitment_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME':'database',
    #     'USER' : 'root',
    #     'PASSWORD' : 'kali',
    #     'HOST' : "127.0.0.1",
    #     "PORT" : "3306",
    # }
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

}

# In production (Render), DATABASE_URL is set to the managed Postgres
# instance's connection string - use it when present. Local dev keeps
# using the sqlite3 file above.
_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(default=_database_url, conn_max_age=600)
from datetime import datetime
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location' : f'{BASE_DIR}/backup/database/'}


#DBBACKUP_FILENAME_TEMPLATE = f"Backup-{datetime.now().strftime('%H_%M_%S-%d_%m_%Y')}.backup"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'  # Or any other time zone



USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# collectstatic (run during the Render build) writes the production bundle
# here; WhiteNoise serves it from there.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# In dev, let WhiteNoise fall back to serving straight from STATICFILES_DIRS
# so nothing breaks if collectstatic hasn't been run locally.
WHITENOISE_USE_FINDERS = DEBUG


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL ='authenticate.Users'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''
# DEFAULT_FROM_EMAIL = ''

